### ISSUE TITLE
Redis missing in README diagram

### ISSUE THREAD

**Issue by zisom-hc** [hashicorp/terraform-aws-terraform-enterprise-hvd#1]
Both active-active and external require the use of an external redis installation, and I see the code is correctly covering this, but the diagram is not reflecting it. It's a small issue but figured it'd be worth pointing out in the case this has not been noticed yet.

**Comment by ml4** [comment]
Thanks for raising this issue.

**Comment by ml4** [comment]
Apologies for the delay. This will be fixed before the end of this month.

**Comment by ml4** [comment]
https://github.com/hashicorp/terraform-aws-terraform-enterprise-hvd/pull/11
