### ISSUE TITLE
Feature request : Support RDS Serverless

### ISSUE THREAD

**Issue by filol** [hashicorp/terraform-aws-terraform-enterprise-hvd#10]
Actually we can't deploy a TFE with a serverless rds. With this options : 
```
rds_aurora_engine_mode           = "provisioned"
 rds_aurora_instance_class        = "db.serverless"
 ```

We get this error : 
```
InvalidDBClusterStateFault: Set the Serverless v2 scaling configuration on the parent DB cluster before creating a Serverless v2 DB instance
```

**Comment by roooms** [comment]
Thanks for raising this @filol I've assigned it to one of our team to consider the way forward.

**Comment by roooms** [comment]
Hi @filol,

We have discussed this internally and reviewed with our R&D team. We haven't tested Terraform Enterprise with serverless RDS and therefore don't have any plans to add support for this in the HVD Module. Having said that, we don't see any reason why this architecture wouldn't work. We don't plan to add this in the HVD Module until our R&D team confirm this would be a working and supported solution. 

If you have a requirement to use TFE with serverless RDS, we recommend engaging with our Customer Success organization to provide more details on the requirement and we can determine the best way forward.

Thanks,
Dan
